<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEs2UUIn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEs2UUIn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEs2UUIn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEs2UUIn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEs2UUIn\App_KernelDevDebugContainer([
    'container.build_hash' => 'Es2UUIn',
    'container.build_id' => '5de654db',
    'container.build_time' => 1744291332,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEs2UUIn');
