<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNrWlxxk\OrderExample_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNrWlxxk/OrderExample_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNrWlxxk.legacy');

    return;
}

if (!\class_exists(OrderExample_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNrWlxxk\OrderExample_KernelDevDebugContainer::class, OrderExample_KernelDevDebugContainer::class, false);
}

return new \ContainerNrWlxxk\OrderExample_KernelDevDebugContainer([
    'container.build_hash' => 'NrWlxxk',
    'container.build_id' => '5b2e54d5',
    'container.build_time' => 1744328524,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNrWlxxk');
