<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'orders_list' => [[], ['_controller' => 'OrderExample\\Controller\\OrderController::list'], [], [['text', '/api/orders/']], [], [], []],
    'orders_create' => [[], ['_controller' => 'OrderExample\\Controller\\OrderController::createOrder'], [], [['text', '/api/orders']], [], [], []],
    'orders_update' => [['uuid'], ['_controller' => 'OrderExample\\Controller\\OrderController::updateOrder'], [], [['variable', '/', '[^/]++', 'uuid', true], ['text', '/api/orders']], [], [], []],
    'orders_show' => [['uuid'], ['_controller' => 'OrderExample\\Controller\\OrderController::getByUuid'], [], [['variable', '/', '[^/]++', 'uuid', true], ['text', '/api/orders']], [], [], []],
    'orders_test' => [[], ['_controller' => 'OrderExample\\Controller\\OrderController::test'], [], [['text', '/api/orders/test']], [], [], []],
    'OrderExample\Controller\OrderController::list' => [[], ['_controller' => 'OrderExample\\Controller\\OrderController::list'], [], [['text', '/api/orders/']], [], [], []],
    'OrderExample\Controller\OrderController::createOrder' => [[], ['_controller' => 'OrderExample\\Controller\\OrderController::createOrder'], [], [['text', '/api/orders']], [], [], []],
    'OrderExample\Controller\OrderController::updateOrder' => [['uuid'], ['_controller' => 'OrderExample\\Controller\\OrderController::updateOrder'], [], [['variable', '/', '[^/]++', 'uuid', true], ['text', '/api/orders']], [], [], []],
    'OrderExample\Controller\OrderController::getByUuid' => [['uuid'], ['_controller' => 'OrderExample\\Controller\\OrderController::getByUuid'], [], [['variable', '/', '[^/]++', 'uuid', true], ['text', '/api/orders']], [], [], []],
    'OrderExample\Controller\OrderController::test' => [[], ['_controller' => 'OrderExample\\Controller\\OrderController::test'], [], [['text', '/api/orders/test']], [], [], []],
];
