<?php

namespace ContainerOkFvdYn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderServiceService extends OrderExample_KernelDevDebugContainer
{
    /**
     * Gets the private 'OrderExample\Service\Order\OrderService' shared autowired service.
     *
     * @return \OrderExample\Service\Order\OrderService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Order/OrderService.php';
        include_once \dirname(__DIR__, 4).'/src/Repository/Order/OrderRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Repository/Order/MySqlOrderRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Repository/Item/ItemRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Repository/Item/MySqlItemRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Order/OrderValidator.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'));

        return $container->privates['OrderExample\\Service\\Order\\OrderService'] = new \OrderExample\Service\Order\OrderService(new \OrderExample\Repository\Order\MySqlOrderRepository($a), new \OrderExample\Repository\Item\MySqlItemRepository($a), new \OrderExample\Service\Order\OrderValidator(($container->privates['validator'] ?? $container->load('getValidatorService'))));
    }
}
