<?php

namespace ContainerOkFvdYn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderControllertestService extends OrderExample_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.d6MmkX2.OrderExample\Controller\OrderController::test()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.d6MmkX2.OrderExample\\Controller\\OrderController::test()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'orderService' => ['privates', 'OrderExample\\Service\\Order\\OrderService', 'getOrderServiceService', true],
        ], [
            'entityManager' => '?',
            'orderService' => 'OrderExample\\Service\\Order\\OrderService',
        ]))->withContext('OrderExample\\Controller\\OrderController::test()', $container);
    }
}
