<?php

namespace ContainerNrWlxxk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V6yNBynService extends OrderExample_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.V6yNByn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.V6yNByn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'OrderExample\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'OrderExample\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'OrderExample\\Controller\\OrderController::createOrder' => ['privates', '.service_locator.9I1pv66.OrderExample\\Controller\\OrderController::createOrder()', 'getOrderControllercreateOrderService', true],
            'OrderExample\\Controller\\OrderController::updateOrder' => ['privates', '.service_locator.9I1pv66.OrderExample\\Controller\\OrderController::updateOrder()', 'getOrderControllerupdateOrderService', true],
            'OrderExample\\Controller\\OrderController::getByUuid' => ['privates', '.service_locator.9I1pv66.OrderExample\\Controller\\OrderController::getByUuid()', 'getOrderControllergetByUuidService', true],
            'OrderExample\\Controller\\OrderController::test' => ['privates', '.service_locator.d6MmkX2.OrderExample\\Controller\\OrderController::test()', 'getOrderControllertestService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'OrderExample\\Controller\\OrderController:createOrder' => ['privates', '.service_locator.9I1pv66.OrderExample\\Controller\\OrderController::createOrder()', 'getOrderControllercreateOrderService', true],
            'OrderExample\\Controller\\OrderController:updateOrder' => ['privates', '.service_locator.9I1pv66.OrderExample\\Controller\\OrderController::updateOrder()', 'getOrderControllerupdateOrderService', true],
            'OrderExample\\Controller\\OrderController:getByUuid' => ['privates', '.service_locator.9I1pv66.OrderExample\\Controller\\OrderController::getByUuid()', 'getOrderControllergetByUuidService', true],
            'OrderExample\\Controller\\OrderController:test' => ['privates', '.service_locator.d6MmkX2.OrderExample\\Controller\\OrderController::test()', 'getOrderControllertestService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'OrderExample\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'OrderExample\\Kernel::loadRoutes' => '?',
            'OrderExample\\Controller\\OrderController::createOrder' => '?',
            'OrderExample\\Controller\\OrderController::updateOrder' => '?',
            'OrderExample\\Controller\\OrderController::getByUuid' => '?',
            'OrderExample\\Controller\\OrderController::test' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'OrderExample\\Controller\\OrderController:createOrder' => '?',
            'OrderExample\\Controller\\OrderController:updateOrder' => '?',
            'OrderExample\\Controller\\OrderController:getByUuid' => '?',
            'OrderExample\\Controller\\OrderController:test' => '?',
        ]);
    }
}
