<?php

namespace ContainerNrWlxxk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderControllergetByUuidService extends OrderExample_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9I1pv66.OrderExample\Controller\OrderController::getByUuid()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9I1pv66.OrderExample\\Controller\\OrderController::getByUuid()'] = ($container->privates['.service_locator.9I1pv66'] ?? $container->load('get_ServiceLocator_9I1pv66Service'))->withContext('OrderExample\\Controller\\OrderController::getByUuid()', $container);
    }
}
